// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nizbbjmvvdddcsdkamkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pemJiam12dmRkZGNzZGthbWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MDU3ODAsImV4cCI6MjA1NTk4MTc4MH0.PG8VckEWLDNc3z0fXAzdqjdEZS7bWbcru7QAIvR5LIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);